version: '2'
services:
  memcached:
    image: memcached:1.4

  app:
    build: .
    image: turistforeningen/focus-checker
    depends_on:
      - memcached
    volumes:
      - .:/app
    volumes_from:
      - secrets

  secrets:
    image: turistforeningen/focus-checker-secrets:v1
    volumes:
      - /secrets
